name: Lobby-System
author: LucaHD_YT
version: 1.0
main: de.lucahdyt.lobbysystem.LobbySystem

commands:
  setwarp:
    description: Setze eigene Spawns für den Teleporter!
  fly:
    dscription: Setze dich in den FlugModus!
  chatclear:
    aliases:
      - cc
    description: Leere denn Chat!
  lobby:
    aliases:
      - l
    description: Teleportiere dich zur Lobby!
  hub:
    description: Teleportiere dich zum Hub!
  lobbysystem:
    aliases:
      - lobbysystem
      - LobbySystem
    description: Zeige die Infos vom Plugin an!
  ec:
    aliases:
      - enderchest
    description: Zeige deine oder andere EnderChests an!
  gamemode:
    aliases:
      - gm
    description: Setze dich in einen anderen SpielModus!